/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTrackOpenTokenRouteImport } from './routes/api/public/track/open/$token'
import { Route as ApiPublicTrackClickTokenRouteImport } from './routes/api/public/track/click/$token'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackOpenTokenRoute = ApiPublicTrackOpenTokenRouteImport.update({
  id: '/api/public/track/open/$token',
  path: '/api/public/track/open/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackClickTokenRoute =
  ApiPublicTrackClickTokenRouteImport.update({
    id: '/api/public/track/click/$token',
    path: '/api/public/track/click/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/track/click/$token': typeof ApiPublicTrackClickTokenRoute
  '/api/public/track/open/$token': typeof ApiPublicTrackOpenTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/track/click/$token': typeof ApiPublicTrackClickTokenRoute
  '/api/public/track/open/$token': typeof ApiPublicTrackOpenTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/track/click/$token': typeof ApiPublicTrackClickTokenRoute
  '/api/public/track/open/$token': typeof ApiPublicTrackOpenTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/public/track/click/$token'
    | '/api/public/track/open/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/public/track/click/$token'
    | '/api/public/track/open/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/public/track/click/$token'
    | '/api/public/track/open/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicTrackClickTokenRoute: typeof ApiPublicTrackClickTokenRoute
  ApiPublicTrackOpenTokenRoute: typeof ApiPublicTrackOpenTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open/$token': {
      id: '/api/public/track/open/$token'
      path: '/api/public/track/open/$token'
      fullPath: '/api/public/track/open/$token'
      preLoaderRoute: typeof ApiPublicTrackOpenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click/$token': {
      id: '/api/public/track/click/$token'
      path: '/api/public/track/click/$token'
      fullPath: '/api/public/track/click/$token'
      preLoaderRoute: typeof ApiPublicTrackClickTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicTrackClickTokenRoute: ApiPublicTrackClickTokenRoute,
  ApiPublicTrackOpenTokenRoute: ApiPublicTrackOpenTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
